# Generated by Django 3.1.4 on 2021-01-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='AbstractUser',
            new_name='status',
        ),
    ]
