# Generated by Django 3.1.4 on 2021-01-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210119_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('edit_profile', 'Can change ProfileModel'), ('see_profile', 'Can view ProfileModel'), ('remove_profile', 'Can delete ProfileModel'), ('create_profile', 'Can add ProfileModel')]},
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
