# Generated by Django 3.1.4 on 2021-01-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210120_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
    ]
