# Generated by Django 3.1.5 on 2021-01-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('change_Profile', 'Can change ProfileModel'), ('view_Profile', 'Can view ProfileModel'), ('delete_Profile', 'Can delete ProfileModel'), ('add_Profile', 'Can add ProfileModel')]},
        ),
    ]
