# Generated by Django 3.1.5 on 2021-02-10 08:51

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210129_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default/index.jpg', upload_to=chat.models.uploadedfile_path),
        ),
    ]
