# Generated by Django 3.1.5 on 2021-02-10 08:58

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210210_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default/index.jpg', upload_to=chat.models.uploadedfile_path),
        ),
    ]
