# Generated by Django 3.1.5 on 2021-02-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210210_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slug',
            new_name='username',
        ),
    ]
